version: '3'
services:
  # PostgreSQL Service
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: forestfire123
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on: 
      - db
    links: 
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: on-failure
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
